# Generated by Django 2.2.11 on 2020-03-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200320_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cash',
            new_name='asset_transfers',
        ),
        migrations.AddField(
            model_name='profile',
            name='avail_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='gross_asset_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
